### ISSUE TITLE
Game randomly crashes (BlockRay NaN)

### ISSUE THREAD

**Issue by OLEGSHA** [OLEGSHA/Progressia#25]
This crash happens completely randomly. It is due to a bug in block selection detection.

Example crashreport:
```
--------------------------------------------------------------------------------
                                Version Provider                                
Version: 999.0.0-2022_01_07
Git commit: dececb458988af641071a913ef02cb78349a4a12
Git branch: master
Build ID: -
--------------------------------------------------------------------------------
                              OS Context Provider                               
OS Name: Windows 10
OS Version: 10.0
OS Architecture: amd64
--------------------------------------------------------------------------------
                              RAM Context Provider                              
Used Memory: 1485 MB
Free Memory: 270 MB
Total Memory: 1756 MB
Max Memory: 4074 MB
--------------------------------------------------------------------------------
                         Java Version Context Provider                          
JVM name: OpenJDK 64-Bit Server VM
Java vendor: Eclipse Adoptium
Java home path: C:\Program Files\Eclipse Adoptium\jdk-17.0.1.12-hotspot
Java Runtime version: 17.0.1+12
Java Runtime name: OpenJDK Runtime Environment
Java version: 17.0.1
JVM version: 17.0.1+12
JVM vendor: Eclipse Adoptium
--------------------------------------------------------------------------------
                             Audio Context Provider                             
OpenAL version: 1.1 ALSOFT 1.19.1
--------------------------------------------------------------------------------
                           Arguments Context Provider                           
Number of arguments: 0 total
--------------------------------------------------------------------------------
                           Language Context Provider                            
Language: en-US
--------------------------------------------------------------------------------
                            Screen Context Provider                             
Refresh rate: 60 Hz
Size: 1920x1017
Fullscreen: disabled
--------------------------------------------------------------------------------
                                   Analyzers                                    
Provided description: 
Uncaught exception in thread Render
--------------------------------------------------------------------------------
Reported at:
	at ru.windcorp.progressia.ProgressiaLauncher.lambda$setupCrashReports$0(ProgressiaLauncher.java:63)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1082)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1077)
	at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2008)

Reported Throwable:
java.lang.IllegalArgumentException: Position contains NaN: (NaN, NaN, NaN)
	at ru.windcorp.progressia.common.world.BlockRay.start(BlockRay.java:51)
	at ru.windcorp.progressia.client.graphics.world.Selection.update(Selection.java:49)
	at ru.windcorp.progressia.client.graphics.world.LocalPlayer.update(LocalPlayer.java:82)
	at ru.windcorp.progressia.client.graphics.world.LayerWorld.doRender(LayerWorld.java:89)
	at ru.windcorp.progressia.client.graphics.Layer.render(Layer.java:90)
	at ru.windcorp.progressia.client.graphics.GUI.render(GUI.java:103)
	at ru.windcorp.progressia.client.graphics.backend.RenderThread.doRender(RenderThread.java:64)
	at ru.windcorp.progressia.client.graphics.backend.RenderThread.render(RenderThread.java:54)
	at ru.windcorp.progressia.client.graphics.backend.RenderThread.mainLoop(RenderThread.java:44)
	at ru.windcorp.progressia.client.graphics.backend.RenderThread.run(RenderThread.java:36)
```

**Comment by nullkat** [comment]
If the player is in an unloaded chunk, his position is NaN.

Does this bug occur when you are actively moving in the world or when you are just standing?

**Comment by OLEGSHA** [comment]
No, it's due to a rare floating-point division by zero when iterating blocks in `BlockRay`. I thought it was almost impossible, but no, apparently it happens time to time. I think it happens when the camera is exactly on the border between two blocks: the algorithm gets 0 distance to the next block and then divides by that at some point.

**Comment by opfromthestart** [comment]
I have been able to reproduce it twice by mining down at a corner, falling down, and then flying back up while looking straight up.

**Comment by OLEGSHA** [comment]
Whoops, my bad. Indeed, it does not have anything to do with BlockRay internals, it is actually a safeguard detecting some problem upstream. We need to dig around the local variables with the debugger to see what might be causing the problem. I tried fooling around in the game for about an hour with no luck. @opfromthestart's method didn't work for me; there should be a more consistent setup...
